In [1]:
import scipy.io
import os
import numpy as np
import random
import json
from numpy import *
import torch
from collections import Counter

In [2]:
# Read again processed files
x_train = np.load("../benchmark/RAW_DATA/PTBXL_SUPERCLASS/x_train.npy", allow_pickle=True)
y_train = np.load("../benchmark/RAW_DATA/PTBXL_SUPERCLASS/y_train.npy", allow_pickle=True)
x_test = np.load("../benchmark/RAW_DATA/PTBXL_SUPERCLASS/x_test.npy", allow_pickle=True)
y_test = np.load("../benchmark/RAW_DATA/PTBXL_SUPERCLASS/y_test.npy", allow_pickle=True)

x_train.shape, x_test.shape

((14594, 1000, 12), (1650, 1000, 12))

In [3]:
y_train[:10], y_test[:10]

(array([0, 0, 0, 0, 0, 0, 0, 2, 0, 0], dtype=object),
 array([0, 0, 0, 0, 0, 2, 1, 0, 0, 0], dtype=object))

In [8]:
Counter(y_train), y_train.shape

(Counter({0: 8157, 2: 2276, 4: 2158, 3: 479, 1: 1524}), (14594,))

In [9]:
Counter(y_test), y_test.shape

(Counter({0: 912, 2: 256, 1: 184, 4: 242, 3: 56}), (1650,))

In [6]:
np.unique(y_train), np.unique(y_test)

(array([0, 1, 2, 3, 4], dtype=object), array([0, 1, 2, 3, 4], dtype=object))

In [7]:
y_train

array([0, 0, 0, ..., 4, 0, 0], dtype=object)